import React from "react";

const sizeClasses = {
  txtBalooBhaijaanRegular42: "font-baloobhaijaan font-normal",
  txtTajawalBlack60: "font-black font-tajawal",
  txtTajawalBold18: "font-bold font-tajawal",
  txtTajawalBold16: "font-bold font-tajawal",
  txtTajawalBold20Gray900: "font-bold font-tajawal",
  txtMontserratRomanMedium135WhiteA700: "font-medium font-montserrat",
  txtTajawalMedium14Bluegray600: "font-medium font-tajawal",
  txtTajawalMedium20Gray40002: "font-medium font-tajawal",
  txtTajawalBold94: "font-bold font-tajawal",
  txtTajawalRegular14Bluegray300: "font-normal font-tajawal",
  txtTajawalMedium2263: "font-medium font-tajawal",
  txtMontserratBold26: "font-bold font-montserrat",
  txtTajawalBold24Bluegray600: "font-bold font-tajawal",
  txtRobotoRomanRegular2194: "font-normal font-roboto",
  txtTajawalRegular18Indigo100: "font-normal font-tajawal",
  txtJFFlatRegular16: "font-jfflat font-normal",
  txtJFFlatRegular18: "font-jfflat font-normal",
  txtTajawalMedium24Pink400: "font-medium font-tajawal",
  txtTajawalMedium20Pink400: "font-medium font-tajawal",
  txtTajawalMedium16Black90087: "font-medium font-tajawal",
  txtTajawalMedium13: "font-medium font-tajawal",
  txtTajawalMedium14: "font-medium font-tajawal",
  txtTajawalMedium16: "font-medium font-tajawal",
  txtTajawalMedium18Bluegray600: "font-medium font-tajawal",
  txtTajawalRegular18Pink400: "font-normal font-tajawal",
  txtTajawalMedium18: "font-medium font-tajawal",
  txtMontserratRomanSemiBold819: "font-montserrat font-semibold",
  txtTajawalBold1329: "font-bold font-tajawal",
  txtTajawalBold1209: "font-bold font-tajawal",
  txtTajawalRegular16Indigo200: "font-normal font-tajawal",
  txtTajawalBold18Black900: "font-bold font-tajawal",
  txtTajawalRegular20: "font-normal font-tajawal",
  txtTajawalMedium20Gray900: "font-medium font-tajawal",
  txtTajawalBold60Black900: "font-bold font-tajawal",
  txtTajawalRegular16WhiteA700a2: "font-normal font-tajawal",
  txtTajawalMedium24Gray900: "font-medium font-tajawal",
  txtTajawalMedium16Black900: "font-medium font-tajawal",
  txtJFFlatMedium13: "font-jfflat font-medium",
  txtTajawalRegular18Black900: "font-normal font-tajawal",
  txtTajawalBold20WhiteA700: "font-bold font-tajawal",
  txtTajawalBold60: "font-bold font-tajawal",
  txtTajawalRegular24: "font-normal font-tajawal",
  txtTajawalMedium32: "font-medium font-tajawal",
  txtTajawalRegular24WhiteA700: "font-normal font-tajawal",
  txtTajawalBold28WhiteA700: "font-bold font-tajawal",
  txtTajawalBold20Orange30003: "font-bold font-tajawal",
  txtTajawalMedium18Black90087: "font-medium font-tajawal",
  txtMontserratRomanMedium135: "font-medium font-montserrat",
  txtMontserratRomanBold22: "font-bold font-montserrat",
  txtPingARLTRegular20: "font-normal font-pingarlt",
  txtTajawalBold40WhiteA700: "font-bold font-tajawal",
  txtTajawalBlack28: "font-black font-tajawal",
  txtTajawalBold40Gray900: "font-bold font-tajawal",
  txtTajawalMedium18WhiteA700: "font-medium font-tajawal",
  txtTajawalRegular18: "font-normal font-tajawal",
  txtTajawalMedium18Teal500: "font-medium font-tajawal",
  txtTajawalRegular16Indigo100: "font-normal font-tajawal",
  txtTajawalRegular13: "font-normal font-tajawal",
  txtWorkSansRomanMedium14: "font-medium font-worksans",
  txtTajawalRegular14: "font-normal font-tajawal",
  txtTajawalRegular16: "font-normal font-tajawal",
  txtTajawalMedium20: "font-medium font-tajawal",
  txtTajawalBold20RedA200: "font-bold font-tajawal",
  txtTajawalBold48: "font-bold font-tajawal",
  txtTajawalMedium24: "font-medium font-tajawal",
  txtTajawalMedium20Bluegray600: "font-medium font-tajawal",
  txtTajawalBold44: "font-bold font-tajawal",
  txtTajawalMedium14Indigo100: "font-medium font-tajawal",
  txtTajawalRegular18Gray90075: "font-normal font-tajawal",
  txtTajawalRegular24Indigo100: "font-normal font-tajawal",
  txtTajawalRegular18Indigo300: "font-normal font-tajawal",
  txtMontserratRomanRegular18: "font-montserrat font-normal",
  txtTajawalRegular1329: "font-normal font-tajawal",
  txtTajawalMedium18Gray900: "font-medium font-tajawal",
  txtTajawalBold40: "font-bold font-tajawal",
  txtTajawalRegular16Bluegray600: "font-normal font-tajawal",
  txtTajawalBlack18: "font-black font-tajawal",
  txtTajawalRegular1209: "font-normal font-tajawal",
  txtTajawalMedium20Black900: "font-medium font-tajawal",
  txtTajawalBold32: "font-bold font-tajawal",
  txtTajawalBold48WhiteA700: "font-bold font-tajawal",
  txtTajawalMedium4: "font-medium font-tajawal",
  txtTajawalBold24WhiteA700: "font-bold font-tajawal",
  txtTajawalMedium20Gray90001: "font-medium font-tajawal",
  txtTajawalBold18WhiteA700: "font-bold font-tajawal",
  txtTajawalRegular16Black90075: "font-normal font-tajawal",
  txtTajawalBold32WhiteA700: "font-bold font-tajawal",
  txtTajawalBold24: "font-bold font-tajawal",
  txtTajawalMedium18Gray40001: "font-medium font-tajawal",
  txtMontserratMedium16: "font-medium font-montserrat",
  txtTajawalBold20: "font-bold font-tajawal",
  txtBalooBhaijaanRegular5263: "font-baloobhaijaan font-normal",
  txtTajawalBold28: "font-bold font-tajawal",
  txtMontserratRomanMedium1848: "font-medium font-montserrat",
  txtTajawalMedium18Indigo300: "font-medium font-tajawal",
  txtTajawalRegular18Gray90087: "font-normal font-tajawal",
  txtTajawalBold16Black900: "font-bold font-tajawal",
  txtTajawalBlack28WhiteA700: "font-black font-tajawal",
  txtTajawalRegular14Indigo20099: "font-normal font-tajawal",
};

const Text = ({ children, className = "", size, as, ...restProps }) => {
  const Component = as || "p";

  return (
    <Component
      className={`text-left ${className} ${size && sizeClasses[size]}`}
      {...restProps}
    >
      {children}
    </Component>
  );
};

export { Text };
