import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/page">Page</Link>
        </li>
        <li>
          <Link to="/page1">Page1</Link>
        </li>
        <li>
          <Link to="/page2">Page2</Link>
        </li>
        <li>
          <Link to="/one">One</Link>
        </li>
        <li>
          <Link to="/two">Two</Link>
        </li>
        <li>
          <Link to="/page3">Page3</Link>
        </li>
        <li>
          <Link to="/page4">Page4</Link>
        </li>
        <li>
          <Link to="/page5">Page5</Link>
        </li>
        <li>
          <Link to="/page6">Page6</Link>
        </li>
        <li>
          <Link to="/three">Three</Link>
        </li>
        <li>
          <Link to="/page7">Page7</Link>
        </li>
        <li>
          <Link to="/one1">One1</Link>
        </li>
        <li>
          <Link to="/two1">Two1</Link>
        </li>
        <li>
          <Link to="/page8">Page8</Link>
        </li>
        <li>
          <Link to="/page9">Page9</Link>
        </li>
        <li>
          <Link to="/page10">Page10</Link>
        </li>
        <li>
          <Link to="/three1">Three1</Link>
        </li>
        <li>
          <Link to="/four">Four</Link>
        </li>
        <li>
          <Link to="/page11">Page11</Link>
        </li>
        <li>
          <Link to="/page12">Page12</Link>
        </li>
        <li>
          <Link to="/five">Five</Link>
        </li>
        <li>
          <Link to="/six">Six</Link>
        </li>
        <li>
          <Link to="/page13">Page13</Link>
        </li>
        <li>
          <Link to="/frame1171276108">Frame1171276108</Link>
        </li>
        <li>
          <Link to="/four1">Four1</Link>
        </li>
        <li>
          <Link to="/five1">Five1</Link>
        </li>
        <li>
          <Link to="/six1">Six1</Link>
        </li>
        <li>
          <Link to="/seven">Seven</Link>
        </li>
        <li>
          <Link to="/one2">One2</Link>
        </li>
        <li>
          <Link to="/eight">Eight</Link>
        </li>
        <li>
          <Link to="/one3">One3</Link>
        </li>
        <li>
          <Link to="/nine">Nine</Link>
        </li>
        <li>
          <Link to="/page14">Page14</Link>
        </li>
        <li>
          <Link to="/page15">Page15</Link>
        </li>
        <li>
          <Link to="/ten">Ten</Link>
        </li>
        <li>
          <Link to="/seven1">Seven1</Link>
        </li>
        <li>
          <Link to="/page16">Page16</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
